blog/urls.py
from django.conf.urls import url
from blog import views

app_name = 'blog'


urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit$', views.UpdatePostView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>\d+)/delete$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/publish$', views.post_publish, name='post_publish'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comments/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comments/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
]

django_medium/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views as blog_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/new/', blog_views.user_register, name='register'),
    path('accounts/login/', blog_views.user_login, name='login'),
    path('accounts/logout/', blog_views.user_logout, name='logout'),
    path(r'', include('blog.urls'))
]

medium/medium/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    text = models.TextField()
    created_date = timezone.now()
    published_date = models.DateTimeField(blank=True, null=True)
    updated_date = timezone.now()

    def publish_update(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comments=True)

    # redirect when instance is saved
    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=250)
    text = models.TextField()
    created_date = timezone.now()
    approved_comment = models.BooleanField(default=False)

    def approve_comment(self):
        self.approved_comment = True
        self.save()

    # redirect when instance is saved
    def get_absolute_url(self):
        return reverse("post_list")

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from blog.models import Comment, Post
from django.contrib.auth.models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = [
            'username',
            'email',
            'password'
        ]


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = [
            'author',
            'title',
            'text'
        ]

        widgets = {
            'author': forms.Select(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'})
        }


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = [
            'author',
            'text'
        ]

        widgets = {
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm, UserRegistrationForm
from django.contrib.auth import authenticate, login, logout
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView
)


class AboutView(TemplateView):
    template_name = 'about.html'


class PostListView(ListView):
    template_name = 'blog/post/list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
    template_name = 'blog/post/detail.html'
    model = Post


class CreatePostView(LoginRequiredMixin, CreateView):
    template_name = 'blog/post/form.html'
    login_url = '/login/'
    redirect_field_name = 'blog/post/detail.html'

    form_class = PostForm
    model = Post


class UpdatePostView(LoginRequiredMixin, UpdateView):
    template_name = 'blog/post/form.html'
    login_url = '/login/'
    redirect_field_name = 'blog/post/detail.html'

    form_class = PostForm
    model = Post


class DraftListView(LoginRequiredMixin, ListView):
    template_name = 'blog/post/list.html'
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True)


# Remove post
@login_required()
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')


# Comments
@login_required()
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish_update()
    return redirect('blog:post_detail', pk=pk)


def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()

            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment/form.html', {'form': form})


@login_required()
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve_comment()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required()
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)


# Login and Registration
@login_required
def user_logout(request):
    logout(request)
    return redirect('/')


def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)

        if form.is_valid():
            user = form.save(commit=True)
            user.set_password(user.password)
            user.save()
            return redirect('blog:post_list')
    else:
        form = UserRegistrationForm

    return render(request, "registration/register.html", {'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return redirect('blog:post_list')
    else:
        return render(request, "registration/login.html", {})

blog/templates/blog/about.html
{% extends 'layout/base.html' %}

{% block body_block %}
    <div class="container">
        <h2 class="mt-3 mb-2 text-center">Django-medium</h2>
        <div class="col-md-8 offset-2">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
    </div>
{% endblock %}

blog/templates/blog/comment/form.html
{% extends 'layout/base.html' %}

{% block body_block %}
    <div class="container">
        <div class="m-4">
            <h3 class="text-center">New comment</h3>
            <form method="POST" class="post-form col-md-6 offset-3">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Post Comment</button>
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post/confirm_delete.html
{% extends 'layout/base.html' %}

{% block body_block %}
    <div class="container mb-4">
        <form action="" method="post" class="delete-form col-md-6 offset-3">
            <h3 class="mt-4">Delete post</h3>
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input class='btn btn-danger' type="submit" value="Confirm" />
        </form>
    </div>
{% endblock %}

blog/templates/blog/post/detail.html
{% extends 'layout/base.html' %}

{% block body_block %}
    <div class="container">
        <div class="m-4">
            <h1>{{ post.title }}</h1>

            {% if post.published_date %}
                <small class="text-muted">{{ post.published_date }}</small>
            {% else %}
                <a class="btn btn-primary" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
            {% endif %}

            {% if user.is_authenticated %}
                <a class="btn btn-success" href="{% url 'blog:post_edit' pk=post.pk %}">Edit</a>
                <a class="btn btn-danger" href="{% url 'blog:post_remove' pk=post.pk %}">Remove</a>
            {% endif %}

            <div class="content">
                <p class='postcontent' >{{ post.text|safe|linebreaksbr }}</p>
            </div>
        </div>
        <div class="post-comments">
            <div class="mt-3">
                {% for comment in post.comments.all %}
                    {% if user.is_authenticated or comment.approved_comment %}
                        <div class="border-top mt-3 pt-3">
                            {{ comment.created_date }}
                            {% if not comment.approved_comment %}
                                <a class="btn btn-danger" href="{% url 'blog:comment_remove' pk=comment.pk %}">Remove</a>
                                <a class="btn btn-success" href="{% url 'blog:comment_approve' pk=comment.pk %}">Approve</a>
                            {% endif %}

                            <p>{{ comment.text|safe|linebreaks }}</p>
                            <p>Posted by: <strong>{{ comment.author }}</strong></p>
                        </div>
                    {% endif %}
                {% empty %}
                    <p>No comments posted.</p>
                {% endfor %}
                <a class="btn btn-primary" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post/form.html
{% extends 'layout/base.html' %}

{% block body_block %}
    <div class="container">
        <h3 class="text-center mt-4">New Post</h3>
        <form method="POST" class="post-form col-md-6 offset-3">
            {% csrf_token %}
            <div class="form-group">
                <label>{{ form.author.label_tag }}</label>
                {{ form.author }}
            </div>
            <div class="form-group">
                <label>{{ form.title.label_tag }}</label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label>{{ form.text.label_tag }}</label>
                {{ form.text }}
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post/list.html
{% extends 'layout/base.html' %}

{% block body_block %}
    <div class="container">
        <div class="list-group m-4">
            {% if not post_list %}
                <p>No available contents...</p>
            {% endif %}
            {% for post in post_list %}
                <a href="{% url 'blog:post_detail' pk=post.pk %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ post.title }}</h5>
                        <small>{{ post.published_date }}</small>
                    </div>
                    <div>
                        <small>By: {{ post.author.username }}</small>
                    </div>
                    <div>
                        <small class="text-muted">Comments: {{ post.comments.count }}</small>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'layout/base.html' %}

{% block body_block %}
    <div class="container">
        <h3 class="text-center mt-4">New Post</h3>
        <form method="POST" class="post-form col-md-6 offset-3">
            {% csrf_token %}
            <div class="form-group">
                <label>{{ form.author.label_tag }}</label>
                {{ form.author }}
            </div>
            <div class="form-group">
                <label>{{ form.title.label_tag }}</label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label>{{ form.text.label_tag }}</label>
                {{ form.text }}
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'layout/base.html' %}

{% block body_block %}
    <div class="container">
        <div class="list-group m-4">
            {% for post in post_list %}
                <a href="{% url 'blog:post_detail' pk=post.pk %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ post.title }}</h5>
                        <small>{{ post.published_date }}</small>
                    </div>
                    <small class="text-muted">Comments: {{ post.approved_comments.count }}</small>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/layout/base.html
<!DOCTYPE html>
{%  load staticfiles %}

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Django-Medium - Just another medium clone made with Django</title>
    <link rel="stylesheet" href="{% static "styles/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "styles/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "styles/theme.css" %}">
    <link rel="stylesheet" href="{% static "scripts/bootstrap.js" %}">
</head>
<body>
    {% include 'layout/header.html' %}
    {% block body_block %}

    {% endblock %}
    {% include 'layout/footer.html' %}
</body>
</html>

blog/templates/layout/footer.html
<footer id="footer">
    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong>Django-Medium</strong>. All Rights Reserved
        </div>
    </div>
</footer>

blog/templates/layout/header.html
<header id="header">
    <div class="container">
        <div id="logo" class="pull-left">
            <h1>
                <a href="{% url 'blog:post_list' %}" class="scrollto">D<span>Medium</span></a>
            </h1>
        </div>
        <nav id="nav-menu-container">
            <ul class="nav-menu">
                <li>
                    <a class="nav-link" href="{% url 'blog:post_list' %}">Home</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'blog:about' %}">About</a>
                </li>
                {% if user.is_authenticated %}
                    <li>
                        <a class="nav-link" href="{% url 'blog:post_draft_list' %}">Drafts</a>
                    </li>
                    <li>
                        <a class="nav-link text-success" href="{% url 'blog:post_new' %}">Create post</a>
                    </li>
                    <li>
                        <a class="nav-link text-danger" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a class="nav-link text-info" href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a class="nav-link text-success" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>